[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "solana==0.35.1",
    "sui-sdk==0.1.1.dev0",
    "python-telegram-bot==21.9",
]
